#!/bin/sh

export XAUTHORITY="$HOME/.config/X11/Xauthority"
export XDG_CURRENT_DESKTOP="bspwm"

xrdb -load ~/.config/X11/Xresources

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

exec $XDG_CURRENT_DESKTOP
