#!/bin/sh

export XDG_CURRENT_DESKTOP="bspwm"

xrdb -load ~/.config/X11/Xresources

rm -f /tmp/startuplock

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

setxkbmap -layout us,ir -option 'grp:alt_shift_toggle' &
setxkbmap -option caps:none

exec $XDG_CURRENT_DESKTOP
