# set font
font pango:JetBrainsMono Nerd Font 13

# move tiling windows via drag & drop by left-clicking into the title bar,
# or left-clicking anywhere into the window while holding the floating modifier.
tiling_drag modifier titlebar

# gaps
gaps inner 15
gaps outer 10
smart_gaps inverse_outer
smart_borders on
hide_edge_borders smart_no_gaps

# default border size
default_border pixel 3

# set position for yad-calendar
for_window [class="Yad" title="yad-calendar"] floating enable move right 840, move up 10
