USER_HOME="${USER_HOME:-"/home/$USER"}"
DOTFILES_DIR="$USER_HOME/.dotfiles"
CORECONFIG_DIR="${CORECONFIG_DIR:-$DOTFILES_DIR/coreconfig}"
. $CORECONFIG_DIR/colors/main.conf

BSPWM_COLOR_BORDER_NORMAL="#212329"
BSPWM_COLOR_BORDER_FOCUSED="#5474b8"
