. $HOME/.dotfiles/coreconfig/colors/main.conf

NVIM_COLOR_STATUS_LINE_NORMAL_BG="#7190D3"
NVIM_COLOR_STATUS_LINE_NORMAL_FG="#14151B"

NVIM_COLOR_STATUS_LINE_INSERT_BG="#98C379"
NVIM_COLOR_STATUS_LINE_INSERT_FG="#14151B"

NVIM_COLOR_STATUS_LINE_VISUAL_BG="#DD9CF0"
NVIM_COLOR_STATUS_LINE_VISUAL_FG="#14151B"

NVIM_COLOR_STATUS_LINE_VISUAL_LINE_BG="#8800B0"
NVIM_COLOR_STATUS_LINE_VISUAL_LINE_FG="#CED1D9"

NVIM_COLOR_STATUS_LINE_VISUAL_BLOCK_BG="#C100F9"
NVIM_COLOR_STATUS_LINE_VISUAL_BLOCK_FG="#14151B"

NVIM_COLOR_STATUS_LINE_COMMAND_BG="#D5916E"
NVIM_COLOR_STATUS_LINE_COMMAND_FG="#14151B"

NVIM_COLOR_STATUS_LINE_REPLACE_BG="#D27078"
NVIM_COLOR_STATUS_LINE_REPLACE_FG="#14151B"

NVIM_COLOR_STATUS_LINE_TERMINAL_BG="#CED1D9"
NVIM_COLOR_STATUS_LINE_TERMINAL_FG="#14151B"

NVIM_COLOR_STATUS_LINE_DIM_BG="#212329"
NVIM_COLOR_STATUS_LINE_DIM_FG="#82838C"


NVIM_COLOR_THEME_BG0="#14151B"
NVIM_COLOR_THEME_BG1="#1B1B20"
NVIM_COLOR_THEME_BG2="#20232F"
NVIM_COLOR_THEME_BG3="#36373C"
NVIM_COLOR_THEME_FG="#CED1D9"
NVIM_COLOR_THEME_FG_DARK="#BEC0CB"
NVIM_COLOR_THEME_FG_LIGHT="#D7DAE7"

NVIM_COLOR_THEME_FG_RED="#D27078"
NVIM_COLOR_THEME_FG_ORANGE="#D5916E"
NVIM_COLOR_THEME_FG_YELLOW="#D2BA4F"
NVIM_COLOR_THEME_FG_GREEN="#98C379"
NVIM_COLOR_THEME_FG_CYAN="#5DA3AC"
NVIM_COLOR_THEME_FG_BLUE="#7E9FE5"
NVIM_COLOR_THEME_FG_PURPLE="#B282C0"
