#!/bin/sh

SCREEN_W=$(xdpyinfo | grep dimension | awk '{print $2}' | sed 's/\(.*\)x.*/\1/')
SCREEN_H=$(xdpyinfo | grep dimension | awk '{print $2}' | sed 's/.*x\(.*\)/\1/')


TOP_PADDING=35
BOTTOM_PADDING=0

BSPWM_WINDOW_GAPS=15
