#!/bin/sh

source $HOME/.config/bspwm/bsp_vars

POLYBAR_SCRIPT="$HOME/.local/bin/polybar_visibility"

while read a m d n _; do
	hide=0
	current_node_state=$(bspc query -T -n | jq -r '.client.state')

	case "$current_node_state" in
	*fullscreen*)
		hide=1
		;;
	*floating*)
		hide=0
		;;
	*)
		hide=0
		;;
	esac

	if [ $hide == 1 ]; then
		$POLYBAR_SCRIPT -h
	else
		$POLYBAR_SCRIPT -s
	fi

done <"$(bspc subscribe -f desktop_focus node_activate node_focus node_state node_remove)"
