#!/bin/sh

source $HOME/.config/bspwm/bsp_vars

POLYBAR_SCRIPT="$HOME/.local/bin/polybar_visibility"

if [ "$1" == "-f" ] || [ "$1" == "--fullscreen" ]; then
	current_node_state=$(bspc query -T -n | jq -r '.client.state')
	if [ "$current_node_state" != "fullscreen" ]; then
		bspc node -t fullscreen
		$POLYBAR_SCRIPT -h
	else
		bspc node -t tiled
		$POLYBAR_SCRIPT -s
	fi

	exit 0
fi

current_layout=$(bspc query -T -d | jq -r '.layout')

if [ "$current_layout" == "tiled" ]; then
	bspc desktop -l monocle
	$POLYBAR_SCRIPT -s
elif [ "$current_layout" == "monocle" ]; then
	bspc desktop -l tiled
	$POLYBAR_SCRIPT -s
else
	exit 0
fi
