#!/usr/bin/sh

source $HOME/.config/bspwm/bsp_vars

###### remove all rules ######
bspc rule -r "*"

###### autostarts ######
$HOME/.local/bin/background &
$HOME/.config/polybar/launch.sh &

xset +dpms dpms 0 600 600 &

pkill sxhkd &
sxhkd &
pgrep -x nm-applet >/dev/null || nm-applet &
pgrep -x xss-lock >/dev/null || xss-lock -l -- $HOME/.local/bin/start_lockscreen &
pgrep -x light >/dev/null || light -I &
pgrep -x xfce-polkit >/dev/null || /usr/lib/xfce-polkit/xfce-polkit &
pgrep -x picom >/dev/null || picom -b --config $HOME/.config/picom/picom.conf &
pgrep -x clementine >/dev/null || clementine &

setxkbmap -layout us,ir -option 'grp:alt_shift_toggle' &

###### desktops ######
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 0

###### ui ######
xsetroot -cursor_name left_ptr

bspc config border_width 1
bspc config bottom_padding 20
bspc config top_padding 0
bspc config window_gap $BSPWM_WINDOW_GAPS
bspc config split_ratio 0.55
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config normal_border_color "#444444"
bspc config focused_border_color "#4080b0"
bspc config single_monocle true
bspc config ignore_ewmh_focus true
bspc config swallow_first_click false
bspc config click_to_focus button1

###### rules ######
bspc rule -a Brave-browser desktop='^2'
bspc rule -a LibreWolf desktop='^2' state=tiled
bspc rule -a 'LibreWolf:*' desktop='^2' state=floating rectangle=900x800+500+140
bspc rule -a 'LibreWolf:Navigator' desktop='^2' state=tiled
bspc rule -a Xdg-desktop-portal-gtk state=floating follow=off focus=on manage=on rectangle=900x800+100+100
bspc rule -a Chromium-browser desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a discord desktop='^4'
bspc rule -a nekoray desktop='^5' state=tiled
bspc rule -a Hiddify desktop='^5' state=tiled
bspc rule -a Clementine desktop='^11' split_ratio=0.6 split_dir=east
bspc rule -a TelegramDesktop desktop='^11' split_ratio=0.4 split_dir=west
bspc rule -a Alacritty rectangle=950x650+0+0
bspc rule -a 'Alacritty-float' state=floating rectangle=1200x800+360+140 focus=on
bspc rule -a Yad state=floating rectangle=400x200+1500+850 focus=on
bspc rule -a qalculate-qt state=floating rectangle=850x650+535+215 focus=on
bspc rule -a ffplay state=floating rectangle=200x100+20+20 follow=on focus=off sticky=on

###### scripts ######

if [ -z $(pgrep bspautohidebar --list-full | grep -E "bspautohidebar") ]; then
  $HOME/.config/bspwm/bspautohidebar &
fi

if [ -z $(pgrep bspfloatpos --list-full | grep -E "bspfloatpos") ]; then
  $HOME/.config/bspwm/bspfloatpos &
fi
