#!/usr/bin/sh

source $HOME/.config/bspwm/bsp_vars

###### remove all rules ######
bspc rule -r "*"

###### autostarts ######
$HOME/.local/bin/background &
$HOME/.config/polybar/launch.sh &

xset +dpms dpms 0 $DPMS_TIME $DPMS_TIME
xset r rate 400 35

pkill sxhkd &
sxhkd &
pgrep -x nm-applet >/dev/null || nm-applet &
pgrep -x xss-lock >/dev/null || xss-lock -l -- $HOME/.local/bin/start_lockscreen &
pgrep -x light >/dev/null || light -I &
pgrep -x xfce-polkit >/dev/null || /usr/lib/xfce-polkit/xfce-polkit &
pgrep -x picom >/dev/null || picom -b --config $HOME/.config/picom/picom.conf &

setxkbmap -layout us,ir -option 'grp:alt_shift_toggle' &
setxkbmap -option caps:none &

###### startups ######
$HOME/.local/bin/startup

###### desktops ######
bspc monitor -d 1 2 3 4 5 6 7 8 9 10 0

###### ui ######
xsetroot -cursor_name left_ptr

bspc config border_width 2
bspc config top_padding $TOP_PADDING
bspc config bottom_padding $BOTTOM_PADDING
bspc config window_gap $BSPWM_WINDOW_GAPS
bspc config split_ratio $SPLIT_RATIO
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config normal_border_color $NORMAL_BORDER_COLOR
bspc config focused_border_color $FOCUSED_BORDER_COLOR
bspc config single_monocle true
bspc config ignore_ewmh_focus true
bspc config swallow_first_click true
bspc config click_to_focus any

###### rules ######
bspc rule -a Brave-browser desktop='^3'
bspc rule -a LibreWolf desktop='^3' state=tiled
bspc rule -a 'LibreWolf:*' desktop='^3' state=floating rectangle=900x800+500+140
bspc rule -a 'LibreWolf:Navigator' desktop='^3' state=tiled
bspc rule -a Xdg-desktop-portal-gtk state=floating follow=off focus=on manage=on rectangle=900x800+100+100
bspc rule -a Chromium-browser desktop='^3'
bspc rule -a firefox desktop='^3'
bspc rule -a discord desktop='^7'
bspc rule -a nekoray desktop='^6' state=tiled
bspc rule -a Hiddify desktop='^6' state=tiled
bspc rule -a 'VirtualBox Manager' desktop='^8' state=tiled
bspc rule -a Clementine desktop='^4' state=tiled
bspc rule -a TelegramDesktop desktop='^5' state=floating rectangle=860x1030+6+42 focus=on
bspc rule -a Alacritty rectangle=950x650+0+0
bspc rule -a 'Alacritty-float' state=floating rectangle=1200x800+360+140 focus=on
bspc rule -a Yad state=floating rectangle=400x200+760+40 focus=on
bspc rule -a qalculate-qt state=floating rectangle=850x650+535+215 focus=on
bspc rule -a ffplay state=floating rectangle=280x210+1615+830 follow=on focus=off sticky=on

###### scripts ######

if [ -z $(pgrep bspfloatpos --list-full | grep -E "bspfloatpos") ]; then
  $HOME/.config/bspwm/bspfloatpos &
fi
