#!/bin/sh

set -a
. "$HOME/.dotfiles/coreconfig/load.sh"
. "$HOME/.dotfiles/coreconfig/require_vars.sh"
set +a

load_init_vars_conf
load_desktop_vars_conf
load_window_classes_conf
load_bspwm_colors

DPMS_TIME=${DPMS_TIME:-600}
XSET_DELAY=${XSET_DELAY:-400}
XSET_RATE=${XSET_RATE:-35}
BSPWM_TOP_PADDING=${BSPWM_TOP_PADDING:-37}
BSPWM_BOTTOM_PADDING=${BSPWM_BOTTOM_PADDING:-0}
BSPWM_WINDOW_GAPS=${BSPWM_WINDOW_GAPS:-0}
BSPWM_SPLIT_RATIO=${BSPWM_SPLIT_RATIO:-0.5}
BSPWM_COLOR_BORDER_NORMAL=${BSPWM_COLOR_BORDER_NORMAL:-"#333333"}
BSPWM_COLOR_BORDER_FOCUSED=${BSPWM_COLOR_BORDER_FOCUSED:-"#333377"}

###### remove all rules ######
bspc rule -r "*"

###### autostarts ######
background &
launch_polybar &

xset +dpms dpms 0 $DPMS_TIME $DPMS_TIME
xset r rate $XSET_DELAY $XSET_RATE

pkill sxhkd &
sxhkd &
pgrep -x nm-applet >/dev/null || nm-applet &
pgrep -x light >/dev/null || light -I &
pgrep -x dunst >/dev/null || dunst &
pgrep -x xfce-polkit >/dev/null || /usr/lib/xfce-polkit/xfce-polkit &
pgrep -x picom >/dev/null || picom -b ${PICOM_CONF_PATH:+--config "$PICOM_CONF_PATH"} &

[[ -n "$START_LOCKSCREEN_SCRIPT_PATH" ]] &&
  pgrep -x xss-lock >/dev/null || xss-lock -l -- "$START_LOCKSCREEN_SCRIPT_PATH" &

setxkbmap -layout us,ir -option 'grp:alt_shift_toggle' &
setxkbmap -option caps:none &

startup &

###### desktops ######
bspc monitor -d 1 2 3 4 7 8 9 10

bspc desktop 1 -l monocle
bspc desktop 2 -l monocle

###### ui ######
xsetroot -cursor_name left_ptr

bspc config border_width 2
bspc config top_padding $BSPWM_TOP_PADDING
bspc config bottom_padding $BSPWM_BOTTOM_PADDING
bspc config window_gap $BSPWM_WINDOW_GAPS
bspc config split_ratio $BSPWM_SPLIT_RATIO
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config normal_border_color $BSPWM_COLOR_BORDER_NORMAL
bspc config focused_border_color $BSPWM_COLOR_BORDER_FOCUSED
bspc config single_monocle true
bspc config ignore_ewmh_focus true
bspc config swallow_first_click false
bspc config click_to_focus any

###### rules ######
bspc rule -a Brave-browser desktop='^3'
bspc rule -a LibreWolf desktop='^3' state=tiled
bspc rule -a 'LibreWolf:*' desktop='^3' state=floating rectangle=900x800+500+140
bspc rule -a 'LibreWolf:Navigator' desktop='^3' state=tiled
bspc rule -a Xdg-desktop-portal-gtk state=floating follow=off focus=on manage=on rectangle=900x800+100+100
bspc rule -a Chromium-browser desktop='^3'
bspc rule -a firefox desktop='^3'
bspc rule -a Zathura desktop='^2' state=tiled
bspc rule -a Hiddify desktop='^6' state=tiled
bspc rule -a 'VirtualBox Manager' desktop='^7' state=tiled
bspc rule -a Clementine desktop='^5' split_ratio=0.6 split_dir=east
bspc rule -a TelegramDesktop desktop='^5' split_ratio=0.4 split_dir=west
bspc rule -a Alacritty rectangle=950x650+0+0
bspc rule -a Yad state=floating rectangle=400x200+760+40 focus=on
bspc rule -a qalculate-qt state=floating rectangle=850x650+535+215 focus=on
bspc rule -a ffplay state=floating rectangle=280x210+1615+830 follow=on focus=off sticky=on

[[ -n "$TERMINAL_FLOAT_CLASS" ]] &&
  bspc rule -a "$TERMINAL_FLOAT_CLASS" state=floating rectangle=1200x800+360+140 focus=on

###### scripts ######
pgrep -f bspfloatpos >/dev/null || bspfloatpos &
