USER_HOME="/home/$USER"

XDG_CURRENT_DESKTOP="bspwm"

XDG_CONFIG_HOME="$HOME/.config"
XDG_DATA_HOME="$HOME/.local/share"
XDG_STATE_HOME="$HOME/.local/state"
XDG_CACHE_HOME="$HOME/.cache"

USER_XDG_CONFIG_HOME="$USER_HOME/.config"
USER_XDG_DATA_HOME="$USER_HOME/.local/share"
USER_XDG_STATE_HOME="$USER_HOME/.local/state"
USER_XDG_CACHE_HOME="$USER_HOME/.cache"

XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"

YAZI_CONFIG_HOME="$XDG_CONFIG_HOME/yazi"

npm_config_prefix="$HOME/.local/node"

CORECONFIG_DIR="$USER_HOME/.dotfiles/coreconfig"
SCRIPTS_DIR="$USER_HOME/.local/bin"

START_LOCKSCREEN_SCRIPT_PATH="$SCRIPTS_DIR/utils/start_lockscreen"
PICOM_CONF_PATH="$XDG_CONFIG_HOME/picom/picom.conf"
POLYBAR_VISIBILITY_SCRIPT_PATH="$SCRIPTS_DIR/bar/polybar_visibility"
BACKGROUND_SCRIPT_PATH="$SCRIPTS_DIR/utils/background"
