GITHUB_USERNAME="SaeedAlian"

NVIM_CONFIG_TYPE="minimal"

MOUNT_DIR="$USER_HOME/mount"
NOTES_DIR="$USER_HOME/documents/notes"
PROJECTS_DIR="$USER_HOME/documents/projects"
WORK_DIR="$USER_HOME/documents/work"
STUDY_DIR="$USER_HOME/documents/study"
SCREEN_CAST_DIR="$USER_HOME/videos/casts"
MUSICS_DIR="$USER_HOME/music"
WALLPAPERS_DIR="$USER_HOME/pictures/wallpapers/walls"
LOCKSCREENS_DIR="$USER_HOME/pictures/wallpapers/lockscreens"
SCREENSHOTS_DIR="$USER_HOME/pictures/screenshots"
