#!/bin/sh

source $HOME/.config/env/env_vars

cachedir="${XDG_CACHE_HOME:-"$HOME/.cache"}"
cache="$cachedir/dmenu_run"

[ ! -e "$cachedir" ] && mkdir -p "$cachedir"

IFS=:
if stest -dqr -n "$cache" $PATH; then
  stest -flx $PATH | sort -u | tee "$cache"

  hplist=()

  IFS=$','
  while read -r line; do
    hplist+=("$line")
  done <<< "$(cat "$HOME/.dotfiles/dmenu/hp.csv")"

  c=""
  i=0

  for a in ${hplist[@]}; do
    if [ $i == 0 ]; then
      c="$a"
    else
      c="$c
$a"
    fi

    i=$((i+1))
  done
  
  t=$(cat "$cache")

  for a in ${hplist[@]}; do
    t=$(echo "$t" | sed "s/^$a$//" | sed '/^[[:space:]]*$/d')
  done

  res="$c
$t"

  echo "$res" > "$cache"
else
	cat "$cache"
fi
