INIT_VARS="vars/init.conf"
SHELL_VARS="vars/shell.conf"
USER_VARS="vars/user.conf"
DESKTOP_VARS="vars/desktop.conf vars/background.conf vars/touchpad.conf vars/trackpoint.conf vars/window_classes.conf"
COLOR_VARS="colors/main.conf colors/xresources.conf colors/bspwm.conf colors/bar.conf colors/alacritty.conf colors/nvim.conf colors/rofi.conf colors/dunst.conf colors/zathura.conf"
